.idea/vcs.xml
=> test commit

app/src/main/java/me/caelumterrae/fbunewsapp/MainActivity.java, app/src/main/java/me/caelumterrae/fbunewsapp/PoliticalActivity.java
=> Mock data added to MainActivity (populateMockData())

app/build.gradle, app/src/main/java/me/caelumterrae/fbunewsapp/FeedAdapter.java, app/src/main/java/me/caelumterrae/fbunewsapp/model/Post.java
Made Post model Parcelable, imported Parcel , and implemented an onClickListener in Feed adapter with Intent. resolves #21
=> Added Intent to Feed Adapter

app/src/main/java/me/caelumterrae/fbunewsapp/DetailsActivity.java, app/src/main/java/me/caelumterrae/fbunewsapp/FeedAdapter.java, app/src/main/java/me/caelumterrae/fbunewsapp/utilities/RelatedAdapter.java, app/src/main/res/layout/activity_details.xml, app/src/main/res/layout/item_related_post.xml
Finished bottom recycler view. Still have to make details scrollable using a scrollview.
=> Advanced ui

app/src/main/java/me/caelumterrae/fbunewsapp/DetailsActivity.java, app/src/main/java/me/caelumterrae/fbunewsapp/model/Post.java
=> DetailsActivity now handles intents

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/me/caelumterrae/fbunewsapp/MainActivity.java, app/src/main/java/me/caelumterrae/fbunewsapp/client/TopNewsClient.java, app/src/main/java/me/caelumterrae/fbunewsapp/model/Post.java
Main activity recyclerview now pulls articles from the newsapi.org
Created working TopNewsClient
Post updated to handle JSON objects from TopNewClient
Resolves #30
=> Top news client

app/src/main/java/me/caelumterrae/fbunewsapp/FeedAdapter.java, app/src/main/java/me/caelumterrae/fbunewsapp/MainActivity.java, app/src/main/res/layout/item_post.xml
=> added UI and rounded edges

app/src/main/java/me/caelumterrae/fbunewsapp/model/Post.java
=> time altered

app/build.gradle, app/src/main/java/me/caelumterrae/fbunewsapp/FeedAdapter.java, app/src/main/res/layout/item_post.xml, app/src/main/res/values/dimen.xml
=> added cardview

app/src/main/java/me/caelumterrae/fbunewsapp/FeedAdapter.java, app/src/main/res/layout/activity_details.xml
=> UI for voting done + fixed bug where populatemockdata doesnt work

app/src/main/java/me/caelumterrae/fbunewsapp/MainActivity.java, app/src/main/java/me/caelumterrae/fbunewsapp/client/TopNewsClient.java, app/src/main/res/layout/activity_main.xml
=> SwipeRefreshLayout added

app/src/main/res/layout/item_post.xml, app/src/main/res/values/styles.xml
=> took away toolbar

app/src/main/java/me/caelumterrae/fbunewsapp/DetailsActivity.java, app/src/main/java/me/caelumterrae/fbunewsapp/MainActivity.java, app/src/main/java/me/caelumterrae/fbunewsapp/utilities/RelatedAdapter.java, app/src/main/res/layout/activity_details.xml, app/src/main/res/layout/item_related_post.xml
=> Changed layout for item_related_post and Details Activity

app/build.gradle, app/src/main/java/me/caelumterrae/fbunewsapp/DetailsActivity.java, app/src/main/java/me/caelumterrae/fbunewsapp/FeedAdapter.java, app/src/main/java/me/caelumterrae/fbunewsapp/MainActivity.java, app/src/main/java/me/caelumterrae/fbunewsapp/client/TopNewsClient.java, app/src/main/java/me/caelumterrae/fbunewsapp/model/Post.java
Dates are now handled differently in the Post class
=> gets relative time on the images as opposed to the actual times. 

app/src/main/java/me/caelumterrae/fbunewsapp/DetailsActivity.java, app/src/main/java/me/caelumterrae/fbunewsapp/PoliticalActivity.java, app/src/main/java/me/caelumterrae/fbunewsapp/client/TopNewsClient.java
=> Upvoting data saved to file with persistence

app/src/main/AndroidManifest.xml, app/src/main/java/me/caelumterrae/fbunewsapp/FeedFragment.java, app/src/main/java/me/caelumterrae/fbunewsapp/PoliticalFragment.java, app/src/main/java/me/caelumterrae/fbunewsapp/SwipeActivity.java
=> Implemented Fragments

app/build.gradle, app/src/main/java/me/caelumterrae/fbunewsapp/utilities/FeedAdapter.java, app/src/main/res/layout/item_post.xml
Resolves #97 but could still be smoothed out
=> Basic pre-loading image progressbar

app/src/main/java/me/caelumterrae/fbunewsapp/client/ParseNewsClient.java, app/src/main/java/me/caelumterrae/fbunewsapp/client/TopNewsClient.java
=> articles do not appear in their own related articles

app/src/main/AndroidManifest.xml, app/src/main/java/me/caelumterrae/fbunewsapp/CreateActivity.java, app/src/main/java/me/caelumterrae/fbunewsapp/PoliticalActivity.java, app/src/main/java/me/caelumterrae/fbunewsapp/SwipeActivity.java, app/src/main/res/layout/activity_create.xml, app/src/main/res/values/colors.xml
=> Category Selection added

app/src/main/java/me/caelumterrae/fbunewsapp/client/TopNewsClient.java, app/src/main/java/me/caelumterrae/fbunewsapp/handlers/TimelineHandler.java
=> getTopHeadlines uses /everything endpoint

app/src/main/java/me/caelumterrae/fbunewsapp/LoginActivity.java
=> User login now valid with persistence

app/src/main/java/me/caelumterrae/fbunewsapp/MainActivity.java, app/src/main/java/me/caelumterrae/fbunewsapp/SwipeActivity.java, app/src/main/java/me/caelumterrae/fbunewsapp/UserFragment.java
=> Can access right user in fragments

app/src/main/java/me/caelumterrae/fbunewsapp/client/TopNewsClient.java, app/src/main/java/me/caelumterrae/fbunewsapp/handlers/TimelineHandler.java, app/src/main/java/me/caelumterrae/fbunewsapp/utility/DateFunctions.java, app/src/main/java/me/caelumterrae/fbunewsapp/utility/Timeline.java
=> Abstraction

app/src/main/java/me/caelumterrae/fbunewsapp/handlers/database/GetLikeHandler.java, app/src/main/java/me/caelumterrae/fbunewsapp/handlers/database/GetUserHandler.java, app/src/main/java/me/caelumterrae/fbunewsapp/model/User.java
=> Finished getUserHandler and getLikeHandler

app/src/main/java/me/caelumterrae/fbunewsapp/client/ParseNewsClient.java, app/src/main/java/me/caelumterrae/fbunewsapp/handlers/database/AddRemoveLikeHandler.java, app/src/main/java/me/caelumterrae/fbunewsapp/model/User.java
Resolves #184 
Resolves #186 
Resolves #187 
Resolves #189
=> FInished all Handlers for the database

app/src/main/java/me/caelumterrae/fbunewsapp/activities/CreateActivity.java, app/src/main/java/me/caelumterrae/fbunewsapp/fragments/FeedFragment.java, app/src/main/java/me/caelumterrae/fbunewsapp/fragments/UserFragment.java, app/src/main/java/me/caelumterrae/fbunewsapp/handlers/database/LoginHandler.java, app/src/main/java/me/caelumterrae/fbunewsapp/handlers/database/SignupHandler.java, app/src/main/res/layout/user.xml
=> cleaned and altered user fragment

app/src/main/AndroidManifest.xml, app/src/main/java/me/caelumterrae/fbunewsapp/activities/CommentActivity.java, app/src/main/res/layout/activity_comment.xml, app/src/main/res/layout/item_comment.xml
=> Finished with making the UI for: CommentActivity.java and item_comment

app/src/main/java/me/caelumterrae/fbunewsapp/handlers/database/GetLikeHandler.java, app/src/main/java/me/caelumterrae/fbunewsapp/math/BetaDis.java
=> Fixed beta distribution where alpha is too small

app/src/main/java/me/caelumterrae/fbunewsapp/model/User.java, app/src/main/res/drawable/edittext_background.xml, app/src/main/res/layout/activity_login.xml, app/src/main/res/layout/item_comment.xml, app/src/main/res/values/styles.xml
=> backend fixed and experimented with some login ui

app/src/main/res/layout/activity_login.xml
=> new version of login screen

app/src/main/java/me/caelumterrae/fbunewsapp/client/ParseNewsClient.java, app/src/main/java/me/caelumterrae/fbunewsapp/fragments/UserFragment.java, app/src/main/java/me/caelumterrae/fbunewsapp/handlers/database/comments/GetNumCommentsHandler.java, app/src/main/res/layout/activity_login.xml
=> comments properly show upon refresh

app/src/main/java/me/caelumterrae/fbunewsapp/adapters/CommentAdapter.java, app/src/main/java/me/caelumterrae/fbunewsapp/model/Comment.java
=> comments show proper profile images on refresh

app/src/main/java/me/caelumterrae/fbunewsapp/client/ParseNewsClient.java
=> getNumLikes client method created

app/src/main/java/me/caelumterrae/fbunewsapp/client/TopNewsClient.java, app/src/main/java/me/caelumterrae/fbunewsapp/fragments/UserFragment.java, app/src/main/java/me/caelumterrae/fbunewsapp/handlers/database/GetLikesHandler.java, app/src/main/java/me/caelumterrae/fbunewsapp/utility/Timeline.java
=> radar chart data now accurate

app/src/main/AndroidManifest.xml, app/src/main/java/me/caelumterrae/fbunewsapp/activities/LoginActivity.java, app/src/main/java/me/caelumterrae/fbunewsapp/adapters/LikesAdapter.java, app/src/main/java/me/caelumterrae/fbunewsapp/fragments/UserFragment.java, app/src/main/java/me/caelumterrae/fbunewsapp/fragments/UserFragmentTabs/UpvotedFragment.java, app/src/main/java/me/caelumterrae/fbunewsapp/handlers/database/GetUserLikesHandler.java, app/src/main/java/me/caelumterrae/fbunewsapp/model/Like.java, app/src/main/res/layout/fragment_upvoted.xml, app/src/main/res/layout/item_like.xml
=> Upvote fragment completed

app/src/main/java/me/caelumterrae/fbunewsapp/fragments/UserFragmentTabs/PoliticalAffiliationFragment.java
Attempting to resolve refresh bug - result unclear as origin of bug is unclear
=> a first attempt at fixing the bugginess

app/src/main/java/me/caelumterrae/fbunewsapp/activities/CommentActivity.java, app/src/main/java/me/caelumterrae/fbunewsapp/activities/DetailsActivity.java, app/src/main/java/me/caelumterrae/fbunewsapp/activities/OtherUserActivity.java, app/src/main/java/me/caelumterrae/fbunewsapp/activities/SwipeActivity.java, app/src/main/java/me/caelumterrae/fbunewsapp/activities/UserActivity.java, app/src/main/java/me/caelumterrae/fbunewsapp/adapters/CommentPostAdapter.java, app/src/main/java/me/caelumterrae/fbunewsapp/adapters/FeedAdapter.java, app/src/main/java/me/caelumterrae/fbunewsapp/utility/SwipeDetector.java, app/src/main/res/layout/activity_comment.xml, app/src/main/res/layout/activity_details.xml, app/src/main/res/layout/activity_other_user.xml, app/src/main/res/layout/activity_user.xml, app/src/main/res/layout/item_post.xml
Can now swipe right all the way from comment back to swipe activity
=> added swiping ui
